name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Build and Deploy
      env:
        JEKYLL_ENV: production
      run: |
        bundle exec jekyll build
        bash _scripts/deploy.sh # 这里可以添加一个脚本来将构建结果部署到 GitHub Pages
